### ISSUE TITLE
Using Galene on augmented data

### ISSUE THREAD

**Issue by akatav** [flimfit/Galene#21]
So, i have 2 photon fluorescence image of many dendrites and synapses (in 2 dimension). Due to raster scanning, each image has motion artifacts from breathing and head movement and heartbeats. My problem is right now, there is no  time lapse of the FOV, ie, the FOV is raster scanned only once. So, if i augment this image (by affine translations, cropping, rotation etc) and feed it to Galene, can i expect motion corrected image as output ?

**Comment by seanwarren** [comment]
Hello, Galene works by using temporal information to correct for motion so you need a timelapse image. One option is to increase your scan rate and acquire time lapses with lower signal which you can then correct in Galene to a single, corrected image
